const dados =
    {
        "state": "GO",
        "cities": [
          "VILA PROPICIO",
          "GAMELEIRA DE GOIAS",
          "IPIRANGA DE GOIAS",
          "CAMPO LIMPO DE GOIAS",
          "VIANÓPOLIS",
          "VARJÃO",
          "URUANA",
          "URUAÇU",
          "UIRAPURU",
          "TROMBAS",
          "TRINDADE",
          "TEREZÓPOLIS DE GOIÁS",
          "TERESINA DE GOIÁS",
          "TAQUARAL DE GOIÁS",
          "SÍTIO D'ABADIA",
          "SIMOLÂNDIA",
          "SILVÂNIA",
          "SENADOR CANEDO",
          "SÃO PATRÍCIO",
          "SÃO MIGUEL DO PASSA QUATRO",
          "SÃO MIGUEL DO ARAGUAIA",
          "SÃO LUÍZ DO NORTE",
          "SÃO JOÃO D'ALIANÇA",
          "SÃO FRANCISCO DE GOIÁS",
          "SÃO DOMINGOS",
          "SANTO ANTÔNIO DE GOIÁS",
          "SANTA TEREZINHA DE GOIÁS",
          "SANTA TEREZA DE GOIÁS",
          "SANTA ROSA DE GOIÁS",
          "SANTA RITA DO NOVO DESTINO",
          "SANTA ISABEL",
          "SANTA FÉ DE GOIÁS",
          "SANTA BÁRBARA DE GOIÁS",
          "RUBIATABA",
          "RIANÁPOLIS",
          "RIALMA",
          "POSSE",
          "PORANGATU",
          "PIRENÓPOLIS",
          "PILAR DE GOIÁS",
          "PETROLINA DE GOIÁS",
          "OURO VERDE DE GOIÁS",
          "NOVO PLANALTO",
          "NOVO BRASIL",
          "NOVA VENEZA",
          "NOVA ROMA",
          "NOVA IGUAÇU DE GOIÁS",
          "NOVA GLÓRIA",
          "NOVA CRIXÁS",
          "NOVA AMÉRICA",
          "NIQUELÂNDIA",
          "NERÓPOLIS",
          "MUTUNÓPOLIS",
          "MUNDO NOVO",
          "MOZARLÂNDIA",
          "MORRO AGUDO DE GOIÁS",
          "MONTIVIDIU DO NORTE",
          "MONTES CLAROS DE GOIÁS",
          "MONTE ALEGRE DE GOIÁS",
          "MINAÇU",
          "MIMOSO DE GOIÁS",
          "MATRINCHÃ",
          "MARA ROSA",
          "MAMBAÍ",
          "LEOPOLDO DE BULHÕES",
          "JUSSARA",
          "JESÚPOLIS",
          "JARAGUÁ",
          "ITAUÇU",
          "ITAPURANGA",
          "ITAPIRAPUÃ",
          "ITAPACI",
          "ITAGUARU",
          "ITAGUARI",
          "ITABERAÍ",
          "INHUMAS",
          "IACIARA",
          "HIDROLINA",
          "HIDROLÂNDIA",
          "HEITORAÍ",
          "GUARINOS",
          "GUARANI DE GOIÁS",
          "GUARAÍTA",
          "GUAPÓ",
          "GOIÁS",
          "GOIANIRA",
          "GOIÂNIA",
          "GOIANÉSIA",
          "GOIANÁPOLIS",
          "DIVINÓPOLIS DE GOIÁS",
          "FORMOSO",
          "FLORES DE GOIÁS",
          "FAZENDA NOVA",
          "FAINA",
          "ESTRELA DO NORTE",
          "DAMOLÂNDIA",
          "DAMIANÓPOLIS",
          "CRIXÁS",
          "CORUMBÁ DE GOIÁS",
          "COLINAS DO SUL",
          "COCALZINHO DE GOIÁS",
          "CERES",
          "CAVALCANTE",
          "CATURAÍ",
          "CARMO DO RIO VERDE",
          "CAMPOS VERDES",
          "CAMPOS BELOS",
          "CAMPINORTE",
          "CAMPINAÇU",
          "CAMPESTRE DE GOIÁS",
          "CALDAZINHA",
          "BURITINÓPOLIS",
          "BRITÂNIA",
          "BRAZABRANTES",
          "BONÓPOLIS",
          "BONFINÓPOLIS",
          "BELA VISTA DE GOIÁS",
          "BARRO ALTO",
          "ARUANÃ",
          "ARAGUAPAZ",
          "ARAGOIÂNIA",
          "ARAÇU",
          "APARECIDA DE GOIÂNIA",
          "ANÁPOLIS",
          "AMARALINA",
          "ALVORADA DO NORTE",
          "ALTO PARAÍSO DE GOIÁS",
          "ALTO HORIZONTE",
          "ALEXÂNIA",
          "ÁGUA FRIA DE GOIÁS",
          "ABADIÂNIA",
          "ABADIA DE GOIÁS"
        ]
      }


export default dados;